import { GalleryHorizontalEnd, Earth, User, Fence, Calendar } from 'lucide-react';
import type { MenuItem } from '../types/navigation';

export const MENU_ITEMS: MenuItem[] = [
  {
    icon: GalleryHorizontalEnd,
    label: 'Cromos',
    href: '/cromos',
    dots: [
      { x: -5, y: -22, size: 4, connectsTo: [1,3] },
      { x: 22, y: -22, size: 3.4, connectsTo: [2] },
      { x: 23, y: 22, size: 5, connectsTo: [3] },
      { x: -4, y: 22, size: 3.8 },
      { x: -15, y: -12, size: 4.5, connectsTo: [5] },
      { x: -14, y: 12, size: 3.4 },
    ],
  },
  {
    icon: Earth,
    label: 'Mapa',
    href: '/mapa',
    dots: [
      { x: -12, y: -22, size: 3.8, connectsTo: [1,5] },
      { x: 12, y: -20, size: 4, connectsTo: [2] },
      { x: 23, y: 0, size: 3.4, connectsTo: [3] },
      { x: 13, y: 22, size: 4.5, connectsTo: [4] },
      { x: -11, y: 21, size: 5, connectsTo: [5] },
      { x: -23, y: 0, size: 3.8 },
    ],
  },
  {
    icon: User,
    label: 'Perfil',
    href: '/perfil',
    dots: [
      { x: 0, y: -22, size: 4.5, connectsTo: [1,5] },
      { x: 9, y: -17, size: 3.4 },
      { x: 10, y: -7, size: 4, connectsTo: [1,3] },
      { x: 0, y: 0, size: 3 },
      { x: -10, y: -6, size: 3.4, connectsTo: [3,5] },
      { x: -9, y: -17, size: 3 },
      { x: 0, y: 7, size: 4, connectsTo: [7,10] },
      { x: 15, y: 10, size: 5 },
      { x: 20, y: 22, size: 3.8, connectsTo: [7] },
      { x: -20, y: 22, size: 3.8, connectsTo: [10] },
      { x: -15, y: 10, size: 3.8 },
    ],
  },
  {
    icon: Fence,
    label: 'Huerto',
    href: '/huerto',
    dots: [
      { x: -22, y: -20, size: 3.4},
      { x: -20, y: 0, size: 3.4, connectsTo: [0,2] },
      { x: -21, y: 20, size: 3.4},
      { x: 0, y: -21, size: 4.5,},
      { x: 0, y: 0, size: 4, connectsTo: [1,3,5,7] },
      { x: 0, y: 22, size: 3.8 },
      { x: 21, y: -20, size: 5 },
      { x: 20, y: 0, size: 3.4, connectsTo: [6,8]},
      { x: 21, y: 20, size: 3.4 },
    ],
  },
  {
    icon: Calendar,
    label: 'Eventos',
    href: '/eventos',
    dots: [
      { x: -9, y: -22, size: 4, connectsTo: [1] },
      { x: -9, y: -9, size: 3.8},
      { x: 9, y: -21, size: 4, connectsTo: [3] },
      { x: 9, y: -10, size: 3.8},
      { x: -22, y: -16, size: 5, connectsTo: [5,7] },
      { x: 22, y: -16, size: 3.4, connectsTo: [6] },
      { x: 21, y: 22, size: 4.5, connectsTo: [7] },
      { x: -22, y: 22, size: 3.8 },
    ],
  },
];